- name: Launch AMI instance(s)
  ec2:
      key_name: "{{ ec2_key_name }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ami_id }}"
      wait: yes
      group_id: "{{ aws_group_id }}"
#     The Count should never be changed higher than 1, unless you want more EC2 instances with the same hostname on them
      count: 1
      vpc_subnet_id: "{{ aws_subnet_id }}" 
      region: "{{ aws_region }}"
      assign_public_ip: "{{ ec2_public_ip }}"
      instance_tags: 
         Name: "{{ hostname }}"
  register: ec2


- name: Add DNS entries for the newly deployed instances
  route53:
      state: present
      private_zone: yes
      zone: "{{ aws_dns_zone }}"
      record: "{{ item.tags.Name }}"
      type: A
      ttl: 7200
      value: "{{ item.private_ip }}"
      wait: yes
  with_items: "{{ ec2.instances }}"

- name: Add new Instance FQDN to group
  add_host:
      name: "{{ item.tags.Name }}"
      groups: ec2-provision
  with_items: "{{ ec2.instances }}"
