- name: Launch AMI instance(s)
  ec2:
      key_name: "{{ ec2_key_name }}"
      #  instance_type: "{{ ec2_instance_type }}"
      instance_type: "{{ cli_instance_type|default('t2.micro') }}"
      image: "{{ ami_id }}"
      wait: yes
      group_id: "{{ aws_group_id }}"
#     The Count should never be changed higher than 1, unless you want more EC2 instances with the same hostname on them
      count: 1
      vpc_subnet_id: "{{ aws_subnet_id }}" 
      region: "{{ aws_region }}"
      assign_public_ip: "{{ ec2_public_ip }}"
      instance_tags: 
         Name: "{{ hostname }}"
  register: ec2

- name: Add DNS entries for the newly deployed instances
  route53:
      state: present
      private_zone: yes
      zone: "{{ aws_dns_zone }}"
      record: "{{ item.tags.Name }}"
      type: A
      ttl: 7200
      value: "{{ item.private_ip }}"
      wait: yes
  with_items: "{{ ec2.instances }}"

- name: Add new Instance FQDN to group
  add_host:
      name: "{{ item.tags.Name }}"
      groups: ec2-provision  
  with_items: "{{ ec2.instances }}"

- name: Add Elastic IP to the newly deployed instance
  ec2_eip:
      device_id: "{{ item }}"
      region: "{{ aws_region }}"
      allow_reassociation: yes
      state: present
      in_vpc: yes
  with_items: "{{ ec2.instance_ids }}"
  when: cli_allocate_elastic_ip|default('false')|bool
