- name: Launch AMI instance(s)
  ec2:
      key_name: ansible_admin
      instance_type: t2.micro
      image: "{{ ami_id }}"
      wait: yes
      group_id: "{{ aws_group_id }}"
      count: 1
      vpc_subnet_id: "{{ aws_subnet_id }}" 
      region: us-east-1
      instance_tags: 
         Name: "{{ hostname }}"
  register: ec2


- name: Add DNS entries for the newly deployed instances
  route53:
      state: present
      private_zone: yes
      zone: "{{ aws_dns_zone }}"
      record: "{{ item.tags.Name }}"
      type: A
      ttl: 7200
      value: "{{ item.private_ip }}"
      wait: yes
  with_items: "{{ ec2.instances }}"


- name: Add server DNS name to provisioning inventory
  lineinfile:
      path: "{{ inventory_dir }}/aws-deploy"
      insertafter: "[aws\\-provision\\-hosts]"
      line: "{{ hostname }}"
