ami_id: "ami-011b3ccf1bd6db744"
aws_group_id: "sg-0a34a97130c2309e9"
aws_subnet_id: "subnet-0ff45370d54a4d62e"
aws_dns_zone: "adahinh.net"
aws_region: "us-east-1"
ec2_instance_type: "t2.micro"
ec2_key_name: "ansible_admin"
ec2_public_ip: "no"

