- name: Deploys AWS EC2 Instances
  hosts: aws-deploy-hosts
  connection: local
  gather_facts: False
  tasks:
      - name: Deploy VMs
        with_items:
            - "{{ lookup('file', 'hosts/aws-deploy-hosts').splitlines() }}"
        include_role:
           name: aws-instance-deploy
        loop_control:
           loop_var: hostname
  environment:
      AWS_ACCESS_KEY: "{{ vault_ec2_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ vault_ec2_secret_key }}"
