- name: Test playbook
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
      - name: Deploy EC2 instance
        ec2:
          key_name: id_rsa
          instance_type: t2.micro
          image: "ami-011b3ccf1bd6db744"
          wait: yes
          group_id: "sg-04b76f9f804dd68cb"
          count: 1
          vpc_subnet_id: subnet-05688d81a2f825718
          region: us-east-1
          instance_tags:
              Name: "{{ item }}"
        register: ec2
        loop: 
           - 'testserver1'
           - 'testserver2'
      - name: Debug ec2 variable
        debug: var=ec2.instances
      - name: Add DNS entries for the newly deployed instances
        route53:
          state: present
          private_zone: yes
          zone: adahinh.net
          record: "{{ item.tags.Name }}.adahinh.net"
          type: A
          ttl: 7200
          value: "{{ item.private_ip }}"
          wait: yes
        with_items: "{{ ec2.instances }}"
               
