- include: set_hostname.yml
  tags: ['hostname']
- include: rhel_subscription.yml
  tags: ['rhel_sub']
- include: install_epel_repo.yml
  tags: ['epel']
- include: config_krb_ad_auth.yml
  tags: ['krb_ad']
#- include: install_and_configure_ntp.yml
#  tags: ['ntp']
#- include: update_all.yml
#  tags: ['update_all']
- include: install_base_packages.yml
  tags: ['base_packages']

- name: Allow password logins to instances
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "PasswordAuthentication no"
      line: "PasswordAuthentication yes"
      backup: yes

- name: Reboot the servers
  reboot:
      reboot_timeout: 3600

